### ISSUE TITLE
Rewrite context if datasetBaseUrl is set

### ISSUE THREAD

**Issue by l00mi** [zazuko/hydra-box#24]
Currently the framing is not working properly if the _datasetBaseUrl_ in Trifid is set.

Two possible solutions:
- Rewrite all mentions of the datasetBaseUrl with the current hostname before framing.
or
- Rewrite the triple stream which is framed.

**Comment by ludovicm67** [comment]
This issue has been closed due to inactivity.

Please open a new issue if this is something that is still needed.
