### ISSUE TITLE
Connection to samvera/hydra & W3C Hydra CG?

### ISSUE THREAD

**Issue by berezovskyi** [zazuko/hydra-box#25]
Hi, does this project have a connection to https://github.com/samvera/hydra or https://www.w3.org/community/hydra/?

(in connection to https://github.com/samvera/hydra/issues/146)

**Comment by ktk** [comment]
Hydra Box is a Hydra based Express middleware for mapping SPARQL queries to Hydra APIs. Configuration of the APIs is described in JSON-LD, Hydra Box will read that and expose the API accordingly.

It's currently developed for a project for a customer and already actively used. But we didn't had the time to properly document it yet.

We also collaborate with Hydra client APIs, in particular Alcaeus. See for example this issue: https://github.com/wikibus/Alcaeus/issues/21

What are you looking for?

**Comment by berezovskyi** [comment]
Thanks for a prompt reply, Adrian. Just so that you know, your reply is still confusing because both of the links above seem to be different RDF linked data projects called Hydra. But from the link to Alcaeus I figured out you are indeed talking about the latter W3C Hydra CG, not the other (older) Hydra. Thanks! I was just trying to clarify things, no specific usage question. Happy holidays!

**Comment by ktk** [comment]
Ah and there is a very simple example with Wikidata here http://wikidata.zazuko.com/

**Comment by berezovskyi** [comment]
Thanks, I will explore it!

**Comment by ktk** [comment]
@berezovskyi yes sorry I did not really get the first link. It's indeed W3C Hydra CG based and we are involved in it as well.
